version: "3"
services:
  app:
    build: ./app
    tty: true
    command: /bin/ash
    ports:
      - 8080:8080
    working_dir: /go/src/github.com/blacknikka/eks-log/
    volumes:
      - "./app/src:/go/src/github.com/blacknikka/eks-log/"
  tf:
    build: ./terraform
    tty: true
    working_dir: /terraform
    volumes:
      - "./terraform/src:/terraform"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
  k8:
    build: ./k8s
    tty: true
    working_dir: /k8s
    privileged: true
    volumes:
      - "./k8s/src:/k8s"
      - "./k8s/config:/root/.kube"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
