containerRegistory: registry.hub.docker.com/
app:
  appName: myapp
  appNameSpace: app
  appImage: repo_app
  appImageTag: latest
  appPort: 8080
  appServicePort: 80
region: ap-northeast-1
log:
  eksName: "/aws/eks/eks-log-eks/cluster"
